language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
script: php codecept.phar run acceptance
